adds new alias in mac

diff --git a/private_readonly_dot_shell_aliases.tmpl b/private_readonly_dot_shell_aliases.tmpl
--- a/private_readonly_dot_shell_aliases.tmpl
+++ b/private_readonly_dot_shell_aliases.tmpl
@@ -12,6 +12,44 @@ alias valencia='curl -4 http://wttr.in/Valencia,Spain'
 alias pbcopy='xsel --clipboard --input'
 alias pbpaste='xsel --clipboard --output'
 
+{{ else if eq .chezmoi.os "darwin" -}}
+
+alias ssmsession='aws ssm start-session --target '
+alias jsonlintall='find . -name "*.json" -exec jsonlint -c -q {} \;'
+aws_sso () {
+        account=$1
+        case $account in
+                (sta) profile=sso_platform_sta_admin  ;;
+                (pro) profile=sso_platform_pro_admin  ;;
+                (prod) profile=sso_platform_pro_admin  ;;
+                (pro_ro) profile=sso_platform_pro_adminro  ;;
+                (*) echo "No profile found bobo!"
+                        return 1 ;;
+        esac
+        export AWS_PROFILE=$profile
+        aws sts get-caller-identity > /dev/null
+        if [ $? -eq 0 ]
+        then
+                return 0
+        fi
+        aws sso login --profile $profile
+}
+ramdisk() {
+  if [ "$1" = "on" ]; then
+  echo creating a 100MB ramdisk:
+  size=$((2 * 1024 * 100))
+  device_name=$(hdiutil attach -nomount ram://${size} | awk '{print $1}')
+  diskutil eraseVolume HFS+ RAMDisk ${device_name}
+  echo created: /Volumes/RAMDisk
+  elif [ "$1" = "off" ]; then
+    echo "Bye RAMDisk... sure? (control+c abort - INTRO byebye)"
+    read
+    hdiutil detach /Volumes/RAMDisk
+  else
+    echo "Uso: ramdisk [on|off]"
+  fi
+}
+
 {{ end -}}
 
 # old fresh: josacar/dotfiles shell/aliases/git.sh
